WP: Stacklight integrations
tcpcloud/salt-formula-rabbitmq pull request #7
Opened 2016-10-12 13:48 UTC by cznewt

2016-10-12 13:58 UTC, simonpasquier commented on rabbitmq/meta/heka.yml
> +  filter:
This filter and the one below will be generated from the alarms that will be defined in the user model. At least this is our current thinking. Obviously we need to flesh out the details and @elemoine is working on it.
So I would drop the metric_collector part for now and focus on the collectd plugins.

2016-10-12 14:51 UTC, cznewt commented on rabbitmq/meta/heka.yml
> +  filter:
Alarm definition should be part of service level metadata models, user may be able to override the parameters but they are autogenerated at default.

2016-10-12 15:06 UTC, elemoine commented on rabbitmq/meta/heka.yml
> +  filter:
@cznewt exactly our thinking.

2016-10-12 15:11 UTC, elemoine commented on rabbitmq/meta/heka.yml
> +  filter:
@cznewt when you say "service level metadata models" do you mean here in `rabbitmq/meta/heka.yml` or in some class file in `metadata/service/`? On our side we were thinking about the latter (`metadata/service/`), which is what the user can override as he likes.

2016-10-13 10:05 UTC, SwannCroiset commented on rabbitmq/meta/heka.yml
> +  filter:
We have a requirement as mentioned by @elemoine: the operator must be able to add/disable/override alarm definitions in the salt-model repo. 

@cznewt I don't think having alarm definitions in <service>/meta/*yml allows the operator to override alarm definitions ?

The heka formulas must consume pillar data (reclass parameters) to generate heka sandbox filters (so called AFD filters + alarm definitions in LUA) for services.
We must follow in someway the actual heka formulas shipping its own heka plugins [0] [1] but declared/classified by other services.
[0] https://github.com/tcpcloud/salt-formula-heka/blob/master/heka/server.sls#L184-L199
[1] https://github.com/tcpcloud/salt-formula-heka/blob/master/metadata/service/server/elastic/shipper.yml

2016-10-13 12:37 UTC, cznewt commented on rabbitmq/meta/heka.yml
> +  filter:
@elemoine @SwannCroiset The support metadata reside inside the salt formulas and get executed within the salt runtime with variables present as are when configuring the service and have access to any system call's or salt module run's outputs. This gives you limitless power to generate whatever you need to you config. Having the default alarms definitions in the same format as other filters removes complexity.
Yes all of the defined models will be  overridable from user defined metadata, the power resides that you have well engineered checks and logic out of box and you can tune it up per need.

2016-10-13 12:47 UTC, simonpasquier commented on rabbitmq/meta/heka.yml
> +  filter:
@cznewt I think we're aligned. We "just" need to develop further our vision on how the alarms artefacts will be generated... As stated initially @elemoine is preparing sthg on the topic.

2016-10-17 07:55 UTC, simonpasquier requested changes

2016-10-17 07:55 UTC, simonpasquier commented on rabbitmq/meta/collectd.yml
> +    template: collectd/files/collectd_check_local_endpoint.conf
this should be "rabbitmq/files/collectd_rabbitmq_info.conf" IIUC

2016-10-17 07:55 UTC, simonpasquier commented on rabbitmq/meta/collectd.yml
> +    password: {{ server.admin.password }}
In general, shall we pass every parameter used by the template like you've done it here for username & password?

2016-10-17 07:56 UTC, simonpasquier commented on rabbitmq/files/collectd_rabbitmq_info.conf
> +{%- from "rabbitmq/map.jinja" import server with context %}
Since `server` isn't used this line can be removed

2016-10-19 14:42 UTC, closed without merging